package com.deepflowia.app.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * Represents a single message in the AI chat interface.
 * This is a UI model and is not persisted in the database directly.
 */
data class ChatMessage(
    val text: String,
    val isFromUser: Boolean,
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * Represents a creation action suggested by the AI.
 * It's a structured format that the ViewModel can interpret.
 */
@Serializable
data class SuggestedAction(
    val type: String, // e.g., "tâche", "habitude"
    val titre: String,
    val details: String? = null,
    val parent_id: String? = null
)

/**
 * Utility to parse a SuggestedAction from a JSON string.
 */
fun parseSuggestedAction(jsonString: String): SuggestedAction? {
    return try {
        // Find the JSON part of the string, which might be embedded in other text
        val jsonStart = jsonString.indexOfFirst { it == '{' }
        val jsonEnd = jsonString.indexOfLast { it == '}' }
        if (jsonStart == -1 || jsonEnd == -1) return null

        val extractedJson = jsonString.substring(jsonStart, jsonEnd + 1)
        Json { ignoreUnknownKeys = true }.decodeFromString<SuggestedAction>(extractedJson)
    } catch (e: Exception) {
        null // Return null if parsing fails for any reason
    }
}


// The following data classes map to the Supabase tables for AI features.

/**
 * Maps to the `ai_pending_actions` table.
 * Stores actions suggested by the AI that are pending user confirmation.
 */
@Serializable
data class AIPendingAction(
    @SerialName("id") val id: String? = null,
    @SerialName("user_id") val userId: String,
    @SerialName("action_type") val actionType: String,
    @SerialName("action_data") val actionData: String, // JSON stored as a string
    @SerialName("created_at") val createdAt: String? = null,
    @SerialName("expires_at") val expiresAt: String? = null
)

/**
 * Maps to the `ai_personality_profiles` table.
 * Stores personality profiles generated by the AI based on user interactions.
 */
@Serializable
data class AIPersonalityProfile(
    @SerialName("id") val id: String? = null,
    @SerialName("user_id") val userId: String,
    @SerialName("profile_data") val profileData: String, // JSON stored as a string
    @SerialName("created_at") val createdAt: String? = null,
    @SerialName("updated_at") val updatedAt: String? = null
)

/**
 * Maps to the `ai_productivity_analysis` table.
 * Stores results from detailed productivity analyses.
 */
@Serializable
data class AIProductivityAnalysis(
    @SerialName("id") val id: String? = null,
    @SerialName("user_id") val userId: String,
    @SerialName("analysis_data") val analysisData: String, // JSON stored as a string
    @SerialName("created_at") val createdAt: String? = null,
    @SerialName("updated_at") val updatedAt: String? = null
)

/**
 * Maps to the `ai_productivity_insights` table.
 * Stores smaller, actionable insights generated by the AI.
 */
@Serializable
data class AIProductivityInsight(
    @SerialName("id") val id: String? = null,
    @SerialName("user_id") val userId: String,
    @SerialName("insights_data") val insightsData: String, // JSON stored as a string
    @SerialName("created_at") val createdAt: String? = null,
    @SerialName("updated_at") val updatedAt: String? = null
)

/**
 * Maps to the `ai_requests` table.
 * Logs requests made to AI services for analytics or rate-limiting.
 */
@Serializable
data class AIRequest(
    @SerialName("id") val id: String? = null,
    @SerialName("user_id") val userId: String?,
    @SerialName("service") val service: String,
    @SerialName("created_at") val createdAt: String? = null
)
